# ============================================
# Initial config (HTTP only - before SSL setup)
# Used ONLY for first-time SSL certificate generation
# After SSL is obtained, switch to proxy.conf
# ============================================

server {
    listen 80;
    server_name auth-service-api.mahamexpo.sa expo-service-api.mahamexpo.sa;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        # Auth Service
        set $backend "http://auth-service:80";
        if ($host = "expo-service-api.mahamexpo.sa") {
            set $backend "http://expo-api:80";
        }
        proxy_pass $backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
